spring.application.name=backend

# 1. CONEXIÓN A LA BASE DE DATOS MYSQL (XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/fitconnect_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. CONFIGURACIÓN DE HIBERNATE / JPA
# "update" hace la magia: lee tus clases de Java y crea/actualiza las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# 3. DEBUGGING
# Esto te mostrará en la consola de VSCode las sentencias SQL que Spring ejecuta por detrás
spring.jpa.show-sql=true